# Lossless source stays in assets/. Export the supplied black/white artwork to
# launcher pixels and a 1-bit C++ array; no drawing library is needed on-device.
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$projectRoot = Split-Path $PSScriptRoot -Parent
$source = [System.Drawing.Bitmap]::new((Join-Path $projectRoot 'assets/gndhog-zero-source.png'))
try {
    foreach ($size in @(100, 112)) {
        $bitmap = [System.Drawing.Bitmap]::new($size, $size)
        $packed = [byte[]]::new(($size * $size) / 8)
        try {
            for ($y = 0; $y -lt $size; $y++) {
                for ($x = 0; $x -lt $size; $x++) {
                    # Center-sampled nearest neighbour: preserve the entire
                    # square badge and its hard edges, without interpolation.
                    $sx = [int][Math]::Floor(($x + 0.5) * $source.Width / $size)
                    $sy = [int][Math]::Floor(($y + 0.5) * $source.Height / $size)
                    $pixel = $source.GetPixel($sx, $sy)
                    $white = (299 * $pixel.R + 587 * $pixel.G + 114 * $pixel.B) -ge 128000
                    $color = if ($white) { [System.Drawing.Color]::White } else { [System.Drawing.Color]::Black }
                    $bitmap.SetPixel($x, $y, $color)
                    if ($white) {
                        $bit = $y * $size + $x
                        $index = [int][Math]::Floor($bit / 8)
                        $packed[$index] = $packed[$index] -bor (128 -shr ($bit % 8))
                    }
                }
            }
            if ($size -eq 100) {
                $bitmap.Save((Join-Path $projectRoot 'assets/gndhog-zero_100.png'), [System.Drawing.Imaging.ImageFormat]::Png)
            } else {
                $lines = [System.Collections.Generic.List[string]]::new()
                $lines.Add('// Generated by tools/pack-mascot.ps1 from the supplied mascot. Do not hand edit.')
                $lines.Add('#pragma once')
                $lines.Add('#include <cstdint>')
                $lines.Add('namespace bf {')
                $lines.Add('inline constexpr int kMascotSize = 112;')
                $lines.Add('inline constexpr uint8_t kMascotBits[] = {')
                for ($i = 0; $i -lt $packed.Length; $i += 14) {
                    $row = $packed[$i..($i + 13)] | ForEach-Object { '0x{0:x2}' -f $_ }
                    $lines.Add('    ' + ($row -join ', ') + ',')
                }
                $lines.Add('};')
                $lines.Add('} // namespace bf')
                [IO.File]::WriteAllText((Join-Path $projectRoot 'src/mascot_data.h'), ($lines -join "`n") + "`n", [Text.UTF8Encoding]::new($false))
            }
        } finally { $bitmap.Dispose() }
    }
} finally { $source.Dispose() }
